### ISSUE TITLE
Get it to support Dark Mode

### ISSUE THREAD

**Issue by Zero3K** [yifanwu/blanknewtab#2]
*subject*

It would be nice if it supported Dark Mode.

**Comment by dmitshur** [comment]
In case it helps, I've found the following 3 very simple files to work well in my testing. They support both light and dark modes, switching between them based on the OS-wide (or browser-wide) preference.

manifest.json:

```JSON
{
	"name": "Blank New Tab",
	"version": "0.0.5",
	"description": "Create a blank new tab without any existing content. Supports light and dark modes.",
	"manifest_version": 3,
	"chrome_url_overrides": {
		"newtab": "newtab.html"
	}
}
```

newtab.html:

```HTML
<html>
	<head>
		<title>New Tab</title>
		<link href="/style.css" rel="stylesheet">
	</head>
</html>
```

style.css:

```CSS
@media (prefers-color-scheme: dark) {
	body {
		background-color: rgb(30, 30, 30);
	}
}
```
